name = "SIMDiffExamples"
uuid = "ff8351d9-12a3-4c2d-a61a-51dfbae68567"
authors = ["Sungho Shin <sshin@anl.gov>"]
version = "0.1.0"

[deps]
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
SIMDiff = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"