name = "ExaModelsExamples"
uuid = "ff8351d9-12a3-4c2d-a61a-51dfbae68567"
authors = ["Sungho Shin <sshin@anl.gov>"]
version = "0.1.0"

[deps]
AmplNLReader = "77dd3d4c-cb1d-5e09-9340-85030ff7ba66"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CPUTime = "a9c8d775-2e2e-55fc-8582-045d282d599e"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLPModelsJuMP = "792afdf1-32c1-5681-94e0-d7bf7a5df49e"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
SnoopPrecompile = "66db9d55-30c0-4569-8b51-7e840670fc0c"
