[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
